import Head from "next/head";
import Cards from "@/component/Cards";
import API from "@/component/API";


export default function Home() {
  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/movie-logo.png" />
      </Head>
      {/* <Cards /> */}
      <API />
    </>
  );
}
